CREATE TABLE IF NOT EXISTS PRICES (
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 BRAND_ID BIGINT NULL,
 START_DATE TIMESTAMP NULL,
 END_DATE TIMESTAMP NULL,
 PRICE_LIST BIGINT NULL,
 PRODUCT_ID BIGINT NULL,
 PRIORITY TINYINT NULL,
 PRICE DECIMAL(14,2) NULL,
 CURR VARCHAR(45) NULL);

COMMIT;